name: Build LeagueMiddlewareService For Win/Mac

on:
  push:
    tags:
      - 'v*.*.*'
      
jobs:
  release:
    name: build and release LeagueMiddlewareService
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v2
      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      # step3: npm i
      - name: Install Dependencies
        run: | 
          npm install
          npm install -g ts-node
      #step4: build
      - name: build windows app
        if: matrix.os == 'windows-latest'
        run: npm run build:exe
      # step5: release
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
